# Generated by Django 5.1.1 on 2024-10-08 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoscliente',
            name='cliente',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='personas.cliente'),
            preserve_default=False,
        ),
    ]
