# Generated by Django 5.1.1 on 2024-10-10 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_prestamos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='libros',
            field=models.ManyToManyField(related_name='libros', through='personas.Prestamos', to='personas.libro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='libros_preferidos',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='personas.libro'),
            preserve_default=False,
        ),
    ]
