# Generated by Django 5.1.1 on 2024-10-17 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_cliente_libros_cliente_libros_preferidos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='tipo',
            new_name='idioma',
        ),
    ]
